version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: wisiva_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wisiva
      MYSQL_USER: wisiva_user
      MYSQL_PASSWORD: wisiva_password
    ports:
      - "3306:3306"
    volumes:
      - wisiva_mysql_data:/var/lib/mysql

volumes:
  wisiva_mysql_data:
